### ISSUE TITLE
Push access?

### ISSUE THREAD

**Issue by tomwhoiscontrary** [diaspora/markdown-it-diaspora-mention#1]
Hi,

You appear to have given me push access to this repository - at least, i got an email from GitHub saying so.

Was this deliberate? If not, you might like to revoke it. If so, let me know what you'd like me to do!

tom
##

**Comment by jhass** [comment]
That's interesting, I don't see you any of those teams from a quick look:

![](http://cloud.aeshna.de/u/mrzyx/screenshots/screenshot_20150109_160735.png)

Maybe we found a Github bug?

Also you don't have the collab or owner tag next to your name in this issue, like I do.

**Comment by jhass** [comment]
@tomwhoiscontrary I sent a message to Github support, here's the reply:

> I can confirm that tomwhoiscontrary does not have push access to diaspora/markdown-it-diaspora-mention.
> 
> I'm not sure what email he is referring to. You might ask him to send us the email (including full headers) so that we can figure out what happened.

**Comment by tomwhoiscontrary** [comment]
Okay, i've looked at the email a bit more closely - it's not addressed to me, it's addressed to developers@pivotallabs.com, but since that's a mailing list i'm on, i received it. Do you have any contributors associated with Pivotal Labs? If so, could they be using that as their email address by mistake?

I'm happy to pass the email on - where should i send it? GitHub support, i guess. Is there a ticket number i can attach?

**Comment by jhass** [comment]
Yes, Pivotal hosted the founders of Diaspora and 2-3 of the Pivotal stuff did contributions and are still in the team. Check https://github.com/orgs/diaspora/people whether you recognize anybody and maybe reach out to them about that ;)

I just used the Contact form you can reach through the link in the footer.

**Comment by tomwhoiscontrary** [comment]
Okay, this sounds like a plausible explanation. I don't recognise any of the people in your organisation, but i'll take it up with the IT guys at work tomorrow and see what i can find out.
